### ISSUE TITLE
Camera doesn't resize accordingly to the browser

### ISSUE THREAD

**Issue by serpentisx** [serpentisx/utopia#10]
When resizing the browser, the camera stays fixed and doesn't resize accordingly to the browser.

**Comment by flexayoung** [comment]
This is probably because the camera is given dimensions when constructed, we might just need to add a set function to fix it

**Comment by serpentisx** [comment]
Yes, exactly! Would be great if this gets fixed.

**Comment by flexayoung** [comment]
Camera will not resize if you expand the browser, and shrink it but no smaller than its original size

**Comment by serpentisx** [comment]
Closed in 77161cbcab0966ee623379b1d7225950e124efe0
